sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tnhung1980/react-docker -f Dockerfile.dev .

script: 
  - docker run -e CI=true tnhung1980/react-docker npm run test